
channels:
  - defaults
dependencies:
  - matplotlib>=3.5.1
  - numpy>=1.21.5
  - param>=1.12.0
  - scipy>=1.7.3
  - sympy>=1.10.1
  - pandas>=1.4.2
  - pytest>=7.1.1
  - pip:
    - absl-py==1.0.0
    - charset-normalizer==2.0.12
    - docopt==0.6.2
    - flatbuffers==2.0
    - jax==0.3.13
    - jaxlib==0.3.10
    - mpmath==1.2.1
    - opt-einsum==3.3.0
    - pipreqs==0.4.11
    - typing-extensions==4.2.0
    - yarg==0.1.9